-- which-key.nvim
-- Useful plugin to show you pending keybinds
-- https://github.com/folke/which-key.nvim

return {
  "folke/which-key.nvim",
  event = "VimEnter",
  opts = {
    delay = 0,
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = "<Up> ",
        Down = "<Down> ",
        Left = "<Left> ",
        Right = "<Right> ",
        C = "<C-…> ",
        M = "<M-…> ",
        D = "<D-…> ",
        S = "<S-…> ",
        CR = "<CR> ",
        Esc = "<Esc> ",
        ScrollWheelDown = "<ScrollWheelDown> ",
        ScrollWheelUp = "<ScrollWheelUp> ",
        NL = "<NL> ",
        BS = "<BS> ",
        Space = "<Space> ",
        Tab = "<Tab> ",
        F1 = "<F1>",
        F2 = "<F2>",
        F3 = "<F3>",
        F4 = "<F4>",
        F5 = "<F5>",
        F6 = "<F6>",
        F7 = "<F7>",
        F8 = "<F8>",
        F9 = "<F9>",
        F10 = "<F10>",
        F11 = "<F11>",
        F12 = "<F12>",
      },
    },
    spec = {
      { "<leader>s", group = "[S]earch" },
      { "<leader>t", group = "[T]oggle" },
      { "<leader>h", group = "Git [H]unk", mode = { "n", "v" } },
      { "<leader>b", group = "[B]uffer" },
      { "<leader>bn", desc = "[B]uffer [N]ext" },
      { "<leader>bp", desc = "[B]uffer [P]revious" },
      { "<leader>u", group = "[U]I toggles" },
      { "<leader>un", desc = "Toggle relative line numbers" },
      { "<leader>uw", desc = "Toggle word wrap" },
      { "<leader>ul", desc = "Toggle list characters" },
      { "<leader>ut", desc = "Cycle colorscheme" },
      { "<leader>c", group = "[C]ode" },
      { "<leader>ca", desc = "[C]ode [A]ctions" },
      { "<leader>cd", desc = "[C]ode show line [D]iagnostics" },
      { "<leader>cf", desc = "[C]ode [F]ormat buffer" },
      { "<leader>cr", desc = "[C]ode [R]ename symbol" },
      { "<leader>l", group = "[L]eetCode" },
      { "<leader>lc", desc = "[L]eetCode [C]onsole panel" },
      { "<leader>ld", desc = "[L]eetCode [D]aily problem" },
      { "<leader>lH", desc = "[L]eetCode s[Ta]ts toggle" },
      { "<leader>lL", desc = "[L]eetCode change [L]anguage" },
      { "<leader>lm", desc = "[L]eetCode [M]enu" },
      { "<leader>lo", desc = "[L]eetCode [O]pen in browser" },
      { "<leader>lr", desc = "[L]eetCode [R]un question" },
      { "<leader>ls", desc = "[L]eetCode [S]ubmit answer" },
      { "<leader>lt", desc = "[L]eetCode [T]est question" },
      { "<leader>lx", desc = "[L]eetCode e[X]it" },
    },
  },
}
