-- which-key.nvim
-- Useful plugin to show you pending keybinds
-- https://github.com/folke/which-key.nvim

return {
  "folke/which-key.nvim",
  event = "VimEnter",
  opts = {
    delay = 300,
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = "<Up> ",
        Down = "<Down> ",
        Left = "<Left> ",
        Right = "<Right> ",
        C = "<C-…> ",
        M = "<M-…> ",
        D = "<D-…> ",
        S = "<S-…> ",
        CR = "<CR> ",
        Esc = "<Esc> ",
        ScrollWheelDown = "<ScrollWheelDown> ",
        ScrollWheelUp = "<ScrollWheelUp> ",
        NL = "<NL> ",
        BS = "<BS> ",
        Space = "<Space> ",
        Tab = "<Tab> ",
        F1 = "<F1>",
        F2 = "<F2>",
        F3 = "<F3>",
        F4 = "<F4>",
        F5 = "<F5>",
        F6 = "<F6>",
        F7 = "<F7>",
        F8 = "<F8>",
        F9 = "<F9>",
        F10 = "<F10>",
        F11 = "<F11>",
        F12 = "<F12>",
      },
    },
    spec = {
      { "<leader>f", group = "[F]ind" },
      { "<leader>g", group = "[G]it" },
      { "<leader>t", group = "[T]oggle" },
      { "<leader>h", desc = "Terminal horizontal" },
      { "<leader>b", group = "[B]uffer" },
      { "<leader>w", group = "[W]orkspace" },
      { "<leader>wa", desc = "[W]orkspace [A]dd folder" },
      { "<leader>wr", desc = "[W]orkspace [R]emove folder" },
      { "<leader>wl", desc = "[W]orkspace [L]ist folders" },
      { "<leader>m", group = "[M]arks / Harpoon" },
      { "<leader>u", group = "[U]I toggles" },
      { "<leader>rn", desc = "Toggle relative line numbers" },
      { "<leader>n", desc = "Toggle line numbers" },
      { "<leader>uw", desc = "Toggle word wrap" },
      { "<leader>ul", desc = "Toggle list characters" },
      { "<leader>uh", desc = "Toggle inlay hints" },
      { "<leader>th", desc = "Theme picker" },
      { "<leader>N", group = "[N]oice" },
      { "<leader>c", group = "[C]ode" },
      { "<leader>ca", desc = "[C]ode [A]ctions" },
      { "<leader>cd", desc = "[C]ode show line [D]iagnostics" },
      { "<leader>cf", desc = "[C]ode [F]ormat buffer" },
      { "<leader>cr", desc = "[C]ode [R]ename symbol" },
      { "<leader>d", group = "[D]iagnostics" },
      { "<leader>ds", desc = "[D]iagnostic [S]et loclist" },
      { "<leader>l", group = "[L]eetCode" },
      { "<leader>ll", desc = "[L]eetCode home" },
      { "<leader>lc", desc = "[L]eetCode [C]onsole panel" },
      { "<leader>ld", desc = "[L]eetCode [D]aily problem" },
      { "<leader>lH", desc = "[L]eetCode s[Ta]ts toggle" },
      { "<leader>lL", desc = "[L]eetCode change [L]anguage" },
      { "<leader>lm", desc = "[L]eetCode [M]enu" },
      { "<leader>lo", desc = "[L]eetCode [O]pen in browser" },
      { "<leader>lr", desc = "[L]eetCode [R]un question" },
      { "<leader>ls", desc = "[L]eetCode [S]ubmit answer" },
      { "<leader>lt", desc = "[L]eetCode [T]est question" },
      { "<leader>lx", desc = "[L]eetCode e[X]it" },
      { "<leader>W", desc = "All keymaps" },
      { "<leader>x", desc = "Close buffer" },
      { "<leader>fm", desc = "[F]ormat buffer" },
      { "<leader>gt", desc = "[G]it [S]tatus" },
      { "<leader>gg", desc = "[G]it Lazy[G]it" },
      { "<leader>gd", desc = "[G]it [D]iffview open" },
      { "<leader>cm", desc = "[C]ommit history" },
      { "<leader>pt", desc = "[P]ick hidden [T]erminal" },
      { "<leader>bt", desc = "[B]uffer [T]oggle tabline" },
      { "<leader>wx", desc = "Close split" },
      { "<leader>w=", desc = "Equalize splits" },
      { "<leader>wk", desc = "Which-key lookup" },
      { "<leader>mm", desc = "Harpoon menu" },
      { "<leader>mA", desc = "Harpoon add file" },
      { "<leader>mn", desc = "Harpoon next" },
      { "<leader>mp", desc = "Harpoon previous" },
      { "<leader>ma", desc = "Find marks" },
      { "<leader>v", desc = "Terminal vertical" },
    },
  },
}
